//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mE3DClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingObject
    {
        public string buildingref { get; set; }
        public string e3dtype { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> thickness { get; set; }
    }
}
